export type { HeaderDef, ShellLayout, ScrollState, CardDef } from './components.impl';
export {
  layoutShell,
  ContentScroller,
  drawHeader,
  handleHeader,
  drawCard,
  drawRow,
  drawSectionTitle,
  drawFooterActions,
  handleFooterActions,
  paintFooterDock,
  heroFooterButton,
  ctaFooterH,
  footerCtaRect,
  clampScroll,
  beginClip,
  endClip,
  wheelScroll,
} from './components.impl';
